// GENERATED by scripts/assets3d-manifest.mjs — do not edit by hand. Re-run it after adding a render.
export type Asset3dKind = "image" | "video" | "model";
export interface Asset3dFile { path: string; bytes: number }
export interface Asset3dFolder { id: string; title: string; kind: Asset3dKind; made: string; note: string; files: Asset3dFile[] }
export const ASSETS_3D: Asset3dFolder[] = [
  {
    "id": "icons",
    "title": "Top-bar icons",
    "kind": "image",
    "made": "tools/blender-shop/scripts/icons3d.py",
    "note": "Sit above the top bars as a 3D overlay. 256 px, transparent.",
    "files": [
      {
        "path": "/icons3d/energy.png",
        "bytes": 17981
      },
      {
        "path": "/icons3d/fame.png",
        "bytes": 61722
      },
      {
        "path": "/icons3d/happiness.png",
        "bytes": 39461
      },
      {
        "path": "/icons3d/heart.png",
        "bytes": 30847
      },
      {
        "path": "/icons3d/money.png",
        "bytes": 66326
      },
      {
        "path": "/icons3d/star-empty.png",
        "bytes": 27240
      },
      {
        "path": "/icons3d/star-full.png",
        "bytes": 26701
      },
      {
        "path": "/icons3d/world.png",
        "bytes": 72987
      }
    ]
  },
  {
    "id": "signing",
    "title": "Signing scene",
    "kind": "image",
    "made": "tools/blender-signing/signing.py",
    "note": "The beats of the 3D signing prototype: talk, contract over the shoulder, wide sign.",
    "files": [
      {
        "path": "/star/signing3d/contract-dark.webp",
        "bytes": 15858
      },
      {
        "path": "/star/signing3d/contract-light.webp",
        "bytes": 15474
      },
      {
        "path": "/star/signing3d/contract-medium.webp",
        "bytes": 15774
      },
      {
        "path": "/star/signing3d/reply-dark.webp",
        "bytes": 15218
      },
      {
        "path": "/star/signing3d/reply-light.webp",
        "bytes": 15138
      },
      {
        "path": "/star/signing3d/reply-medium.webp",
        "bytes": 15474
      },
      {
        "path": "/star/signing3d/signed-dark.webp",
        "bytes": 19148
      },
      {
        "path": "/star/signing3d/signed-light.webp",
        "bytes": 19424
      },
      {
        "path": "/star/signing3d/signed-medium.webp",
        "bytes": 19370
      },
      {
        "path": "/star/signing3d/signing-dark.webp",
        "bytes": 19232
      },
      {
        "path": "/star/signing3d/signing-light.webp",
        "bytes": 19362
      },
      {
        "path": "/star/signing3d/signing-medium.webp",
        "bytes": 19424
      },
      {
        "path": "/star/signing3d/talk-dark.webp",
        "bytes": 19192
      },
      {
        "path": "/star/signing3d/talk-light.webp",
        "bytes": 19180
      },
      {
        "path": "/star/signing3d/talk-medium.webp",
        "bytes": 19184
      }
    ]
  },
  {
    "id": "backdrops",
    "title": "Generated backdrops",
    "kind": "image",
    "made": "Image generator (not Blender)",
    "note": "Generated pictures used as a style and light reference, or behind a scene.",
    "files": [
      {
        "path": "/star/signing3d/room-golden-hour.webp",
        "bytes": 98404
      }
    ]
  },
  {
    "id": "boots",
    "title": "Shop: boots",
    "kind": "image",
    "made": "tools/blender-shop/scripts/boot.py",
    "note": "7 boots × 5 levels.",
    "files": [
      {
        "path": "/shop/boot-control-L1.webp",
        "bytes": 13906
      },
      {
        "path": "/shop/boot-control-L2.webp",
        "bytes": 15158
      },
      {
        "path": "/shop/boot-control-L3.webp",
        "bytes": 15928
      },
      {
        "path": "/shop/boot-control-L4.webp",
        "bytes": 15446
      },
      {
        "path": "/shop/boot-control-L5.webp",
        "bytes": 16620
      },
      {
        "path": "/shop/boot-curl-L1.webp",
        "bytes": 13922
      },
      {
        "path": "/shop/boot-curl-L2.webp",
        "bytes": 15176
      },
      {
        "path": "/shop/boot-curl-L3.webp",
        "bytes": 15942
      },
      {
        "path": "/shop/boot-curl-L4.webp",
        "bytes": 15484
      },
      {
        "path": "/shop/boot-curl-L5.webp",
        "bytes": 16252
      },
      {
        "path": "/shop/boot-elite-L1.webp",
        "bytes": 13492
      },
      {
        "path": "/shop/boot-elite-L2.webp",
        "bytes": 15054
      },
      {
        "path": "/shop/boot-elite-L3.webp",
        "bytes": 15690
      },
      {
        "path": "/shop/boot-elite-L4.webp",
        "bytes": 15450
      },
      {
        "path": "/shop/boot-elite-L5.webp",
        "bytes": 16532
      },
      {
        "path": "/shop/boot-maestro-L1.webp",
        "bytes": 14072
      },
      {
        "path": "/shop/boot-maestro-L2.webp",
        "bytes": 15090
      },
      {
        "path": "/shop/boot-maestro-L3.webp",
        "bytes": 15876
      },
      {
        "path": "/shop/boot-maestro-L4.webp",
        "bytes": 15646
      },
      {
        "path": "/shop/boot-maestro-L5.webp",
        "bytes": 16308
      },
      {
        "path": "/shop/boot-power-L1.webp",
        "bytes": 13932
      },
      {
        "path": "/shop/boot-power-L2.webp",
        "bytes": 15282
      },
      {
        "path": "/shop/boot-power-L3.webp",
        "bytes": 16092
      },
      {
        "path": "/shop/boot-power-L4.webp",
        "bytes": 15666
      },
      {
        "path": "/shop/boot-power-L5.webp",
        "bytes": 16366
      },
      {
        "path": "/shop/boot-speed-L1.webp",
        "bytes": 13788
      },
      {
        "path": "/shop/boot-speed-L2.webp",
        "bytes": 14500
      },
      {
        "path": "/shop/boot-speed-L3.webp",
        "bytes": 15194
      },
      {
        "path": "/shop/boot-speed-L4.webp",
        "bytes": 14896
      },
      {
        "path": "/shop/boot-speed-L5.webp",
        "bytes": 15446
      },
      {
        "path": "/shop/boot-starter-L1.webp",
        "bytes": 13222
      },
      {
        "path": "/shop/boot-starter-L2.webp",
        "bytes": 13576
      },
      {
        "path": "/shop/boot-starter-L3.webp",
        "bytes": 13566
      },
      {
        "path": "/shop/boot-starter-L4.webp",
        "bytes": 13066
      },
      {
        "path": "/shop/boot-starter-L5.webp",
        "bytes": 13938
      }
    ]
  },
  {
    "id": "cars",
    "title": "Shop: cars and bikes",
    "kind": "image",
    "made": "tools/blender-shop/scripts/{car,cars,bikes}.py",
    "note": "",
    "files": [
      {
        "path": "/shop/bike-L1.webp",
        "bytes": 30864
      },
      {
        "path": "/shop/bike-L2.webp",
        "bytes": 22684
      },
      {
        "path": "/shop/bike-L3.webp",
        "bytes": 29858
      },
      {
        "path": "/shop/bike-L4.webp",
        "bytes": 22842
      },
      {
        "path": "/shop/bike-L5.webp",
        "bytes": 28218
      },
      {
        "path": "/shop/car-1-L1.webp",
        "bytes": 15766
      },
      {
        "path": "/shop/car-1-L2.webp",
        "bytes": 16972
      },
      {
        "path": "/shop/car-1-L3.webp",
        "bytes": 16280
      },
      {
        "path": "/shop/car-1-L4.webp",
        "bytes": 15418
      },
      {
        "path": "/shop/car-1-L5.webp",
        "bytes": 15232
      },
      {
        "path": "/shop/car-2-L1.webp",
        "bytes": 16344
      },
      {
        "path": "/shop/car-2-L2.webp",
        "bytes": 17776
      },
      {
        "path": "/shop/car-2-L3.webp",
        "bytes": 17350
      },
      {
        "path": "/shop/car-2-L4.webp",
        "bytes": 16704
      },
      {
        "path": "/shop/car-2-L5.webp",
        "bytes": 20240
      },
      {
        "path": "/shop/car-3-L1.webp",
        "bytes": 16274
      },
      {
        "path": "/shop/car-3-L2.webp",
        "bytes": 16680
      },
      {
        "path": "/shop/car-3-L3.webp",
        "bytes": 16204
      },
      {
        "path": "/shop/car-3-L4.webp",
        "bytes": 15890
      },
      {
        "path": "/shop/car-3-L5.webp",
        "bytes": 16996
      },
      {
        "path": "/shop/car-4-L1.webp",
        "bytes": 14474
      },
      {
        "path": "/shop/car-4-L2.webp",
        "bytes": 15616
      },
      {
        "path": "/shop/car-4-L3.webp",
        "bytes": 16260
      },
      {
        "path": "/shop/car-4-L4.webp",
        "bytes": 16312
      },
      {
        "path": "/shop/car-4-L5.webp",
        "bytes": 16894
      },
      {
        "path": "/shop/classic-L1.webp",
        "bytes": 16026
      },
      {
        "path": "/shop/classic-L2.webp",
        "bytes": 17106
      },
      {
        "path": "/shop/classic-L3.webp",
        "bytes": 17480
      },
      {
        "path": "/shop/classic-L4.webp",
        "bytes": 16980
      },
      {
        "path": "/shop/classic-L5.webp",
        "bytes": 19602
      },
      {
        "path": "/shop/suv-L1.webp",
        "bytes": 18820
      },
      {
        "path": "/shop/suv-L2.webp",
        "bytes": 19944
      },
      {
        "path": "/shop/suv-L3.webp",
        "bytes": 19084
      },
      {
        "path": "/shop/suv-L4.webp",
        "bytes": 17926
      },
      {
        "path": "/shop/suv-L5.webp",
        "bytes": 19246
      }
    ]
  },
  {
    "id": "homes",
    "title": "Shop: homes",
    "kind": "image",
    "made": "tools/blender-shop/scripts/{house,homes_a,homes_b,homes_c}.py",
    "note": "",
    "files": [
      {
        "path": "/shop/estate-L1.webp",
        "bytes": 23918
      },
      {
        "path": "/shop/estate-L2.webp",
        "bytes": 22272
      },
      {
        "path": "/shop/estate-L3.webp",
        "bytes": 21214
      },
      {
        "path": "/shop/estate-L4.webp",
        "bytes": 21728
      },
      {
        "path": "/shop/estate-L5.webp",
        "bytes": 23230
      },
      {
        "path": "/shop/flat-1-L1.webp",
        "bytes": 20260
      },
      {
        "path": "/shop/flat-1-L2.webp",
        "bytes": 19844
      },
      {
        "path": "/shop/flat-1-L3.webp",
        "bytes": 20872
      },
      {
        "path": "/shop/flat-1-L4.webp",
        "bytes": 21174
      },
      {
        "path": "/shop/flat-1-L5.webp",
        "bytes": 21056
      },
      {
        "path": "/shop/flat-2-L1.webp",
        "bytes": 20842
      },
      {
        "path": "/shop/flat-2-L2.webp",
        "bytes": 20904
      },
      {
        "path": "/shop/flat-2-L3.webp",
        "bytes": 22896
      },
      {
        "path": "/shop/flat-2-L4.webp",
        "bytes": 20044
      },
      {
        "path": "/shop/flat-2-L5.webp",
        "bytes": 22494
      },
      {
        "path": "/shop/house-1-L1.webp",
        "bytes": 18360
      },
      {
        "path": "/shop/house-1-L2.webp",
        "bytes": 19134
      },
      {
        "path": "/shop/house-1-L3.webp",
        "bytes": 19918
      },
      {
        "path": "/shop/house-1-L4.webp",
        "bytes": 21634
      },
      {
        "path": "/shop/house-1-L5.webp",
        "bytes": 23288
      },
      {
        "path": "/shop/house-2-L1.webp",
        "bytes": 20344
      },
      {
        "path": "/shop/house-2-L2.webp",
        "bytes": 21610
      },
      {
        "path": "/shop/house-2-L3.webp",
        "bytes": 22310
      },
      {
        "path": "/shop/house-2-L4.webp",
        "bytes": 26178
      },
      {
        "path": "/shop/house-2-L5.webp",
        "bytes": 27826
      },
      {
        "path": "/shop/penthouse-L1.webp",
        "bytes": 20148
      },
      {
        "path": "/shop/penthouse-L2.webp",
        "bytes": 20262
      },
      {
        "path": "/shop/penthouse-L3.webp",
        "bytes": 20762
      },
      {
        "path": "/shop/penthouse-L4.webp",
        "bytes": 20620
      },
      {
        "path": "/shop/penthouse-L5.webp",
        "bytes": 22434
      },
      {
        "path": "/shop/stable-L1.webp",
        "bytes": 27516
      },
      {
        "path": "/shop/stable-L2.webp",
        "bytes": 21978
      },
      {
        "path": "/shop/stable-L3.webp",
        "bytes": 25018
      },
      {
        "path": "/shop/stable-L4.webp",
        "bytes": 22748
      },
      {
        "path": "/shop/stable-L5.webp",
        "bytes": 27060
      }
    ]
  },
  {
    "id": "holiday",
    "title": "Shop: holiday",
    "kind": "image",
    "made": "tools/blender-shop/scripts/{jets,homes_c}.py",
    "note": "",
    "files": [
      {
        "path": "/shop/island-L1.webp",
        "bytes": 17118
      },
      {
        "path": "/shop/island-L2.webp",
        "bytes": 25164
      },
      {
        "path": "/shop/island-L3.webp",
        "bytes": 22662
      },
      {
        "path": "/shop/island-L4.webp",
        "bytes": 21024
      },
      {
        "path": "/shop/island-L5.webp",
        "bytes": 20156
      },
      {
        "path": "/shop/jet-L1.webp",
        "bytes": 22810
      },
      {
        "path": "/shop/jet-L2.webp",
        "bytes": 20186
      },
      {
        "path": "/shop/jet-L3.webp",
        "bytes": 22456
      },
      {
        "path": "/shop/jet-L4.webp",
        "bytes": 19926
      },
      {
        "path": "/shop/jet-L5.webp",
        "bytes": 18830
      },
      {
        "path": "/shop/villa-L1.webp",
        "bytes": 17816
      },
      {
        "path": "/shop/villa-L2.webp",
        "bytes": 20262
      },
      {
        "path": "/shop/villa-L3.webp",
        "bytes": 21650
      },
      {
        "path": "/shop/villa-L4.webp",
        "bytes": 21772
      },
      {
        "path": "/shop/villa-L5.webp",
        "bytes": 21074
      }
    ]
  },
  {
    "id": "drip",
    "title": "Shop: drip",
    "kind": "image",
    "made": "tools/blender-shop/scripts/drip.py",
    "note": "",
    "files": [
      {
        "path": "/shop/art-L1.webp",
        "bytes": 20646
      },
      {
        "path": "/shop/art-L2.webp",
        "bytes": 19652
      },
      {
        "path": "/shop/art-L3.webp",
        "bytes": 20354
      },
      {
        "path": "/shop/art-L4.webp",
        "bytes": 19328
      },
      {
        "path": "/shop/art-L5.webp",
        "bytes": 19454
      },
      {
        "path": "/shop/diamond-L1.webp",
        "bytes": 13122
      },
      {
        "path": "/shop/diamond-L2.webp",
        "bytes": 13610
      },
      {
        "path": "/shop/diamond-L3.webp",
        "bytes": 14612
      },
      {
        "path": "/shop/diamond-L4.webp",
        "bytes": 15804
      },
      {
        "path": "/shop/diamond-L5.webp",
        "bytes": 16866
      },
      {
        "path": "/shop/gold-L1.webp",
        "bytes": 20258
      },
      {
        "path": "/shop/gold-L2.webp",
        "bytes": 21110
      },
      {
        "path": "/shop/gold-L3.webp",
        "bytes": 23032
      },
      {
        "path": "/shop/gold-L4.webp",
        "bytes": 22990
      },
      {
        "path": "/shop/gold-L5.webp",
        "bytes": 21238
      },
      {
        "path": "/shop/rolex-L1.webp",
        "bytes": 22202
      },
      {
        "path": "/shop/rolex-L2.webp",
        "bytes": 21450
      },
      {
        "path": "/shop/rolex-L3.webp",
        "bytes": 20896
      },
      {
        "path": "/shop/rolex-L4.webp",
        "bytes": 22826
      },
      {
        "path": "/shop/rolex-L5.webp",
        "bytes": 24384
      },
      {
        "path": "/shop/silver-L1.webp",
        "bytes": 12852
      },
      {
        "path": "/shop/silver-L2.webp",
        "bytes": 13972
      },
      {
        "path": "/shop/silver-L3.webp",
        "bytes": 15428
      },
      {
        "path": "/shop/silver-L4.webp",
        "bytes": 17682
      },
      {
        "path": "/shop/silver-L5.webp",
        "bytes": 17556
      },
      {
        "path": "/shop/suit-L1.webp",
        "bytes": 18328
      },
      {
        "path": "/shop/suit-L2.webp",
        "bytes": 17814
      },
      {
        "path": "/shop/suit-L3.webp",
        "bytes": 18974
      },
      {
        "path": "/shop/suit-L4.webp",
        "bytes": 17732
      },
      {
        "path": "/shop/suit-L5.webp",
        "bytes": 20478
      }
    ]
  },
  {
    "id": "gadgets",
    "title": "Shop: gadgets",
    "kind": "image",
    "made": "tools/blender-shop/scripts/gadgets.py",
    "note": "",
    "files": [
      {
        "path": "/shop/console-L1.webp",
        "bytes": 16040
      },
      {
        "path": "/shop/console-L2.webp",
        "bytes": 20674
      },
      {
        "path": "/shop/console-L3.webp",
        "bytes": 16416
      },
      {
        "path": "/shop/console-L4.webp",
        "bytes": 19758
      },
      {
        "path": "/shop/console-L5.webp",
        "bytes": 17040
      },
      {
        "path": "/shop/gaming-pc-L1.webp",
        "bytes": 18896
      },
      {
        "path": "/shop/gaming-pc-L2.webp",
        "bytes": 18228
      },
      {
        "path": "/shop/gaming-pc-L3.webp",
        "bytes": 19990
      },
      {
        "path": "/shop/gaming-pc-L4.webp",
        "bytes": 22598
      },
      {
        "path": "/shop/gaming-pc-L5.webp",
        "bytes": 22130
      },
      {
        "path": "/shop/headphones-L1.webp",
        "bytes": 9592
      },
      {
        "path": "/shop/headphones-L2.webp",
        "bytes": 20122
      },
      {
        "path": "/shop/headphones-L3.webp",
        "bytes": 19796
      },
      {
        "path": "/shop/headphones-L4.webp",
        "bytes": 21106
      },
      {
        "path": "/shop/headphones-L5.webp",
        "bytes": 24304
      },
      {
        "path": "/shop/music-L1.webp",
        "bytes": 13702
      },
      {
        "path": "/shop/music-L2.webp",
        "bytes": 16352
      },
      {
        "path": "/shop/music-L3.webp",
        "bytes": 16488
      },
      {
        "path": "/shop/music-L4.webp",
        "bytes": 18500
      },
      {
        "path": "/shop/music-L5.webp",
        "bytes": 20768
      },
      {
        "path": "/shop/phone-L1.webp",
        "bytes": 16732
      },
      {
        "path": "/shop/smartwatch-L1.webp",
        "bytes": 16276
      },
      {
        "path": "/shop/smartwatch-L2.webp",
        "bytes": 15912
      },
      {
        "path": "/shop/smartwatch-L3.webp",
        "bytes": 15386
      },
      {
        "path": "/shop/smartwatch-L4.webp",
        "bytes": 17286
      },
      {
        "path": "/shop/smartwatch-L5.webp",
        "bytes": 18486
      },
      {
        "path": "/shop/tablet-L1.webp",
        "bytes": 16966
      },
      {
        "path": "/shop/tablet-L2.webp",
        "bytes": 17964
      },
      {
        "path": "/shop/tablet-L3.webp",
        "bytes": 18468
      },
      {
        "path": "/shop/tablet-L4.webp",
        "bytes": 16422
      },
      {
        "path": "/shop/tablet-L5.webp",
        "bytes": 17144
      },
      {
        "path": "/shop/tv-L1.webp",
        "bytes": 15632
      },
      {
        "path": "/shop/tv-L2.webp",
        "bytes": 16976
      },
      {
        "path": "/shop/tv-L3.webp",
        "bytes": 16132
      },
      {
        "path": "/shop/tv-L4.webp",
        "bytes": 12924
      },
      {
        "path": "/shop/tv-L5.webp",
        "bytes": 19144
      }
    ]
  },
  {
    "id": "store",
    "title": "Store: coins, boosts, accessories",
    "kind": "image",
    "made": "tools/blender-shop/scripts/store.py",
    "note": "",
    "files": [
      {
        "path": "/shop/store/acc-armband-classic.webp",
        "bytes": 11652
      },
      {
        "path": "/shop/store/acc-armband-rainbow.webp",
        "bytes": 11978
      },
      {
        "path": "/shop/store/acc-boots-blackout.webp",
        "bytes": 15332
      },
      {
        "path": "/shop/store/acc-boots-gold.webp",
        "bytes": 15170
      },
      {
        "path": "/shop/store/acc-boots-volt.webp",
        "bytes": 14122
      },
      {
        "path": "/shop/store/acc-gloves-black.webp",
        "bytes": 19716
      },
      {
        "path": "/shop/store/acc-gloves-gold.webp",
        "bytes": 21460
      },
      {
        "path": "/shop/store/acc-headband-ninja.webp",
        "bytes": 14504
      },
      {
        "path": "/shop/store/acc-headband-white.webp",
        "bytes": 13170
      },
      {
        "path": "/shop/store/acc-sleeves-black.webp",
        "bytes": 13432
      },
      {
        "path": "/shop/store/acc-sleeves-white.webp",
        "bytes": 11446
      },
      {
        "path": "/shop/store/acc-snood-black.webp",
        "bytes": 12088
      },
      {
        "path": "/shop/store/acc-tape-white.webp",
        "bytes": 12658
      },
      {
        "path": "/shop/store/boost-stat.webp",
        "bytes": 12706
      },
      {
        "path": "/shop/store/boost-training.webp",
        "bytes": 13248
      },
      {
        "path": "/shop/store/coins-bag.webp",
        "bytes": 25480
      },
      {
        "path": "/shop/store/coins-chest.webp",
        "bytes": 21776
      },
      {
        "path": "/shop/store/coins-handful.webp",
        "bytes": 20938
      },
      {
        "path": "/shop/store/coins-pouch.webp",
        "bytes": 23286
      },
      {
        "path": "/shop/store/coins-stadium.webp",
        "bytes": 28822
      },
      {
        "path": "/shop/store/coins-vault.webp",
        "bytes": 23798
      }
    ]
  },
  {
    "id": "footballer",
    "title": "Blender footballer: stills",
    "kind": "image",
    "made": "tools/blender-footballer/scripts",
    "note": "Each pose is a layer pack (base, light, kit masks, crest, number) the browser recolours into any club.",
    "files": [
      {
        "path": "/star/blender/hair.jpg",
        "bytes": 201992
      },
      {
        "path": "/star/blender/layers/celebrate/base.webp",
        "bytes": 79272
      },
      {
        "path": "/star/blender/layers/hero/base.webp",
        "bytes": 73366
      },
      {
        "path": "/star/blender/layers/hips/base.webp",
        "bytes": 82028
      },
      {
        "path": "/star/blender/layers/idle/base.webp",
        "bytes": 79836
      },
      {
        "path": "/star/blender/layers/kneeslide/base.webp",
        "bytes": 67456
      },
      {
        "path": "/star/blender/layers/point/base.webp",
        "bytes": 77912
      },
      {
        "path": "/star/blender/mockup-home.jpg",
        "bytes": 109955
      }
    ]
  },
  {
    "id": "clips",
    "title": "Blender footballer: clips",
    "kind": "video",
    "made": "tools/blender-footballer/scripts",
    "note": "Rendered in Chelsea's kit; a .webm copy and a .jpg poster sit next to each.",
    "files": [
      {
        "path": "/star/blender/clips/celebrate.mp4",
        "bytes": 210682
      },
      {
        "path": "/star/blender/clips/idle.mp4",
        "bytes": 240096
      },
      {
        "path": "/star/blender/clips/kneeslide.mp4",
        "bytes": 162436
      }
    ]
  },
  {
    "id": "match",
    "title": "Match view proposal",
    "kind": "image",
    "made": "tools/blender-signing/match_look.py",
    "note": "Blender players seen from the 2D match's own camera, and a before/after still. A proposal (Harry P2-74).",
    "files": [
      {
        "path": "/star/area3d/match-blender-before-after.jpg",
        "bytes": 125553
      },
      {
        "path": "/star/area3d/match-blender.jpg",
        "bytes": 31470
      },
      {
        "path": "/star/area3d/match-sprite-away-hips.png",
        "bytes": 56567
      },
      {
        "path": "/star/area3d/match-sprite-away-idle.png",
        "bytes": 53954
      },
      {
        "path": "/star/area3d/match-sprite-home-hips.png",
        "bytes": 58223
      },
      {
        "path": "/star/area3d/match-sprite-home-idle.png",
        "bytes": 55844
      }
    ]
  },
  {
    "id": "models",
    "title": "3D models (live in the browser)",
    "kind": "model",
    "made": "tools/shop3d/build_assets.py",
    "note": "Loaded by three.js on the 3D Shop page. CC0 Quaternius body (LICENSE.txt in the same folder).",
    "files": [
      {
        "path": "/star/shop3d/anims.glb",
        "bytes": 292124
      },
      {
        "path": "/star/shop3d/character.glb",
        "bytes": 997248
      }
    ]
  },
  {
    "id": "shopitems",
    "title": "3D shop: boots and cars (live in the browser)",
    "kind": "model",
    "made": "tools/shop3d/export_items.py (from tools/blender-shop/scripts/{boot,car,cars}.py)",
    "note": "The shop's own Blender boots (level 3) and cars, cut down for a phone and Draco-compressed. Shown on plinths and the turntable in the 3D shop.",
    "files": [
      {
        "path": "/star/shop3d/items/boot-control.glb",
        "bytes": 68120
      },
      {
        "path": "/star/shop3d/items/boot-curl.glb",
        "bytes": 69376
      },
      {
        "path": "/star/shop3d/items/boot-elite.glb",
        "bytes": 67056
      },
      {
        "path": "/star/shop3d/items/boot-maestro.glb",
        "bytes": 68632
      },
      {
        "path": "/star/shop3d/items/boot-power.glb",
        "bytes": 68060
      },
      {
        "path": "/star/shop3d/items/boot-speed.glb",
        "bytes": 69144
      },
      {
        "path": "/star/shop3d/items/boot-starter.glb",
        "bytes": 66808
      },
      {
        "path": "/star/shop3d/items/car-1.glb",
        "bytes": 166728
      },
      {
        "path": "/star/shop3d/items/car-2.glb",
        "bytes": 171532
      },
      {
        "path": "/star/shop3d/items/car-3.glb",
        "bytes": 200088
      },
      {
        "path": "/star/shop3d/items/car-4.glb",
        "bytes": 168800
      },
      {
        "path": "/star/shop3d/items/car-classic.glb",
        "bytes": 200612
      },
      {
        "path": "/star/shop3d/items/car-suv.glb",
        "bytes": 167936
      }
    ]
  }
];
