"""The 3D icons that sit ABOVE the top bars (v0.24, Harry P1-37/P1-38:
"have the lightning sit above, like in 3D above it, kind of like an overlay";
"have a 3D Earth generated by Blender sit above the bar").

One style for all of them: a chunky, glossy "toy" object, turned a little to
the left so its thickness shows, lit by the same studio as the shop pictures,
no floor and no shadow, transparent background. Rendered at 512 and scaled to
256 in post (crisper edges than rendering at 256).

usage: python icons3d.py -- <name> <out.png> [samples] [size]
names: energy world fame happiness money heart star-full star-empty
Everything is modelled in code. No brands, no outside files.
"""
import sys, os, math
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bpy
from mathutils import Vector, Matrix
import studio as S
from kit import box, cyl, sph, torus, link, convert_curves


# ------------------------------------------------------------ puffy shapes
def puffy(name, pts, mat, extrude=0.16, bevel=0.10, bres=6):
    """A flat outline (x, z) turned into a soft, pillowy 3D badge: the curve
    is filled, pushed out both ways and its edge rounded. This is the one
    building block that gives the bolt, the star and the heart the same look."""
    cu = bpy.data.curves.new(name, 'CURVE')
    cu.dimensions = '2D'
    cu.fill_mode = 'BOTH'
    cu.extrude = extrude
    cu.bevel_depth = bevel
    cu.bevel_resolution = bres
    cu.resolution_u = 4
    sp = cu.splines.new('POLY')
    sp.points.add(len(pts) - 1)
    for p, (x, z) in zip(sp.points, pts):
        p.co = (x, z, 0, 1)
    sp.use_cyclic_u = True
    ob = bpy.data.objects.new(name, cu)
    link(ob)
    # a 2D curve lies in X-Y; stand it up so it faces the camera (-Y).
    ob.rotation_euler = (math.pi / 2, 0, 0)
    cu.materials.append(mat)
    ob = convert_curves([ob])[0]
    for p in ob.data.polygons:
        p.use_smooth = True
    return ob


def star_pts(r_out=1.0, r_in=0.48, n=5):
    pts = []
    for k in range(2 * n):
        r = r_out if k % 2 == 0 else r_in
        a = math.pi / 2 + k * math.pi / n
        pts.append((r * math.cos(a), r * math.sin(a)))
    return pts


def heart_pts(n=96):
    """The classic heart curve, with its two sharp points blunted (a rounded
    bevel on a hairline cusp throws a spike out of the shape)."""
    pts = []
    for k in range(n):
        t = 2 * math.pi * k / n
        if t < 0.30 or t > 2 * math.pi - 0.30 or abs(t - math.pi) < 0.10:
            continue
        x = 16 * math.sin(t) ** 3
        z = 13 * math.cos(t) - 5 * math.cos(2 * t) - 2 * math.cos(3 * t) - math.cos(4 * t)
        pts.append((x / 16.0, z / 16.0 + 0.1))
    return pts


BOLT = [(0.10, 1.05), (0.66, 1.05), (0.30, 0.20), (0.70, 0.20), (-0.22, -1.08), (0.02, -0.08), (-0.40, -0.08)]


# ------------------------------------------------------------ materials
def glossy(name, col, rough=0.18, coat=1.0, emission=None, es=0.0):
    return S.principled(name, col, rough=rough, coat=coat, coat_rough=0.04, spec=0.6, emission=emission, emission_strength=es)


def gold(name='IconGold', rough=0.2):
    return S.principled(name, (*S.srgb((1.0, 0.79, 0.30)), 1), rough=rough, metal=1.0, coat=0.6, coat_rough=0.05)


def earth_mat():
    """Oceans, land, ice caps from layered noise — no map image."""
    m = S.principled('Earth', '#1d6fd1', rough=0.35, coat=0.5, coat_rough=0.08)
    nt = m.node_tree; b = nt.nodes['Principled BSDF']
    tc = S.node(m, 'ShaderNodeTexCoord')
    n1 = S.node(m, 'ShaderNodeTexNoise')
    n1.inputs['Scale'].default_value = 1.6
    n1.inputs['Detail'].default_value = 9
    n1.inputs['Roughness'].default_value = 0.62
    n1.noise_dimensions = '4D'
    n1.inputs['W'].default_value = 7.3
    S.link(m, tc.outputs['Object'], n1.inputs['Vector'])
    ramp = S.node(m, 'ShaderNodeValToRGB')
    cr = ramp.color_ramp
    cr.elements[0].position = 0.0; cr.elements[0].color = (*S.srgb('#0b3f9e'), 1)
    cr.elements[1].position = 0.50; cr.elements[1].color = (*S.srgb('#1f7fe0'), 1)
    e = cr.elements.new(0.535); e.color = (*S.srgb('#e9d38f'), 1)
    e = cr.elements.new(0.55); e.color = (*S.srgb('#3fae3a'), 1)
    e = cr.elements.new(0.68); e.color = (*S.srgb('#2b8a2e'), 1)
    e = cr.elements.new(0.80); e.color = (*S.srgb('#8a7a45'), 1)
    S.link(m, n1.outputs['Fac'], ramp.inputs['Fac'])
    # ice caps: white near the poles
    sep = S.node(m, 'ShaderNodeSeparateXYZ'); S.link(m, tc.outputs['Object'], sep.inputs[0])
    ab = S.node(m, 'ShaderNodeMath'); ab.operation = 'ABSOLUTE'; S.link(m, sep.outputs['Z'], ab.inputs[0])
    cap = S.node(m, 'ShaderNodeMapRange')
    cap.inputs['From Min'].default_value = 0.80; cap.inputs['From Max'].default_value = 0.86
    S.link(m, ab.outputs['Value'], cap.inputs['Value'])
    mix = S.node(m, 'ShaderNodeMix'); mix.data_type = 'RGBA'
    S.link(m, ramp.outputs['Color'], mix.inputs['A'])
    mix.inputs['B'].default_value = (0.95, 0.97, 1.0, 1)
    S.link(m, cap.outputs['Result'], mix.inputs['Factor'])
    S.link(m, mix.outputs['Result'], b.inputs['Base Color'])
    # land is rough, sea is shiny
    rr = S.node(m, 'ShaderNodeMapRange')
    rr.inputs['From Min'].default_value = 0.53; rr.inputs['From Max'].default_value = 0.56
    rr.inputs['To Min'].default_value = 0.12; rr.inputs['To Max'].default_value = 0.75
    S.link(m, n1.outputs['Fac'], rr.inputs['Value'])
    S.link(m, rr.outputs['Result'], b.inputs['Roughness'])
    return m


def cloud_mat():
    m = bpy.data.materials.new('Clouds'); m.use_nodes = True
    nt = m.node_tree
    for n in list(nt.nodes):
        nt.nodes.remove(n)
    out = nt.nodes.new('ShaderNodeOutputMaterial')
    tc = nt.nodes.new('ShaderNodeTexCoord')
    nz = nt.nodes.new('ShaderNodeTexNoise')
    nz.inputs['Scale'].default_value = 3.2; nz.inputs['Detail'].default_value = 6; nz.inputs['Roughness'].default_value = 0.6
    nt.links.new(tc.outputs['Object'], nz.inputs['Vector'])
    ramp = nt.nodes.new('ShaderNodeValToRGB')
    ramp.color_ramp.elements[0].position = 0.56; ramp.color_ramp.elements[0].color = (0, 0, 0, 1)
    ramp.color_ramp.elements[1].position = 0.70; ramp.color_ramp.elements[1].color = (1, 1, 1, 1)
    nt.links.new(nz.outputs['Fac'], ramp.inputs['Fac'])
    white = nt.nodes.new('ShaderNodeBsdfDiffuse'); white.inputs['Color'].default_value = (1, 1, 1, 1)
    clear = nt.nodes.new('ShaderNodeBsdfTransparent')
    # atmosphere: a thin blue rim that brightens at the edge of the globe
    lw = nt.nodes.new('ShaderNodeLayerWeight'); lw.inputs['Blend'].default_value = 0.35
    glow = nt.nodes.new('ShaderNodeEmission'); glow.inputs['Color'].default_value = (*S.srgb('#7cc8ff'), 1); glow.inputs['Strength'].default_value = 1.6
    add = nt.nodes.new('ShaderNodeAddShader')
    rimpow = nt.nodes.new('ShaderNodeMath'); rimpow.operation = 'POWER'; rimpow.inputs[1].default_value = 2.5
    nt.links.new(lw.outputs['Facing'], rimpow.inputs[0])
    mix_rim = nt.nodes.new('ShaderNodeMixShader')
    nt.links.new(rimpow.outputs['Value'], mix_rim.inputs['Fac'])
    nt.links.new(clear.outputs[0], mix_rim.inputs[1])
    nt.links.new(glow.outputs[0], mix_rim.inputs[2])
    mix = nt.nodes.new('ShaderNodeMixShader')
    nt.links.new(ramp.outputs['Color'], mix.inputs['Fac'])
    nt.links.new(mix_rim.outputs[0], mix.inputs[1])
    nt.links.new(white.outputs[0], mix.inputs[2])
    nt.links.new(mix.outputs[0], out.inputs['Surface'])
    m.blend_method = 'BLEND' if hasattr(m, 'blend_method') else None
    return m


# ------------------------------------------------------------ the icons
def make_energy():
    m = glossy('Bolt', '#ffd21f', rough=0.16, emission='#ffb800', es=0.25)
    o = puffy('Bolt', BOLT, m, extrude=0.17, bevel=0.11)
    return [o], dict(turn=-22, tilt=6, expo=-0.25)


def make_world():
    g = sph('Earth', (0, 0, 0), 1.0, earth_mat(), seg=96, rings=48)
    c = sph('Clouds', (0, 0, 0), 1.025, cloud_mat(), seg=96, rings=48)
    for o in (g, c):
        o.rotation_euler = (math.radians(18), math.radians(-12), math.radians(40))
    return [g, c], dict(turn=0, tilt=0, frame=[g], fill=0.80, expo=-0.15)


def make_fame():
    """A gold crown: a band, five points with a ball on each, red and blue stones."""
    gm = gold('Crown')
    ruby = S.principled('Ruby', '#d0142c', rough=0.05, coat=1.0, coat_rough=0.02, spec=1.0)
    sapph = S.principled('Sapph', '#1d4ed8', rough=0.05, coat=1.0, coat_rough=0.02, spec=1.0)
    parts = []
    band = cyl('Band', (0, 0, -0.35), 1.0, 0.42, verts=96, mat=gm, bevel=0.04)
    sol = band.modifiers.new('sol', 'SOLIDIFY'); sol.thickness = 0.12
    # hollow it: remove the caps so the solidify gives a ring
    import bmesh
    bm = bmesh.new(); bm.from_mesh(band.data)
    caps = [f for f in bm.faces if abs(f.normal.z) > 0.9]
    bmesh.ops.delete(bm, geom=caps, context='FACES'); bm.to_mesh(band.data); bm.free()
    parts.append(band)
    parts.append(torus('RimLo', (0, 0, -0.56), 1.03, 0.055, axis='Z', mat=gm, major=96))
    parts.append(torus('RimHi', (0, 0, -0.14), 1.03, 0.05, axis='Z', mat=gm, major=96))
    n = 5
    for k in range(n):
        a = 2 * math.pi * k / n + math.pi / 2
        x, y = math.cos(a) * 0.97, math.sin(a) * 0.97
        sp = cyl(f'Spike{k}', (x, y, 0.22), 0.30, 0.78, verts=4, mat=gm, r2=0.02, bevel=0.03)
        sp.rotation_euler = (0, 0, a + math.pi / 4)
        sp.scale = (1.0, 0.32, 1.0)
        parts.append(sp)
        parts.append(sph(f'Ball{k}', (x * 1.0, y * 1.0, 0.66), 0.11, gm, seg=24, rings=12))
        gx, gy = math.cos(a) * 1.07, math.sin(a) * 1.07
        gem = sph(f'Gem{k}', (gx, gy, -0.35), 0.12, ruby if k % 2 == 0 else sapph, scale=(1, 0.55, 1.15), seg=24, rings=12)
        gem.rotation_euler = (0, 0, a + math.pi / 2)
        parts.append(gem)
    for o in parts:
        o.matrix_world = Matrix.Rotation(math.radians(14), 4, 'X') @ o.matrix_world
    return parts, dict(turn=-15, tilt=0, fill=0.84, expo=-0.35)


def make_happiness():
    """A round, glossy smiley: warm yellow, dark eyes, a curved smile, pink cheeks."""
    face = glossy('Face', '#ffce2e', rough=0.22)
    dark = glossy('Eye', '#3b2410', rough=0.15)
    pink = S.principled('Cheek', '#ff6fa8', rough=0.45, alpha=1.0)
    parts = [sph('Head', (0, 0, 0), 1.0, face, scale=(1, 0.86, 1), seg=96, rings=48)]
    for sx in (-1, 1):
        e = sph(f'Eye{sx}', (0.34 * sx, -0.80, 0.24), 0.13, dark, scale=(0.8, 0.5, 1.25), seg=32, rings=16)
        parts.append(e)
        c = sph(f'Cheek{sx}', (0.60 * sx, -0.62, -0.12), 0.17, pink, scale=(1.0, 0.35, 0.65), seg=32, rings=16)
        c.rotation_euler = (0, 0, math.radians(-38 * sx))
        parts.append(c)
    # the smile: a curved tube following the front of the face
    from kit import tube
    pts = []
    for k in range(13):
        t = math.radians(-60 + 120 * k / 12)
        x = 0.46 * math.sin(t)
        z = -0.20 - 0.30 * math.cos(t) + 0.06
        y = -0.86 * math.sqrt(max(0.0, 1 - x * x - z * z)) - 0.012
        pts.append((x, y, z))
    sm = tube('Smile', pts, 0.055, dark, res=6)
    parts += convert_curves([sm])
    return parts, dict(turn=-10, tilt=4, frame=[parts[0]], fill=0.80, expo=-0.35)


def make_heart():
    m = glossy('Heart', '#ff3d7f', rough=0.16)
    o = puffy('Heart', heart_pts(), m, extrude=0.22, bevel=0.12)
    return [o], dict(turn=-20, tilt=6, expo=-0.30)


def make_money():
    """A thick gold coin with a raised star (the game's money sign is ★)."""
    gm = S.principled('Coin', (*S.srgb((1.0, 0.80, 0.26)), 1), rough=0.28, metal=0.75, coat=1.0, coat_rough=0.05, emission='#ffb000', emission_strength=0.10)
    deep = S.principled('CoinDeep', (*S.srgb((0.95, 0.62, 0.12)), 1), rough=0.45, metal=0.4, coat=0.5)
    parts = []
    body = cyl('Coin', (0, 0, 0), 1.0, 0.24, axis='Y', verts=96, mat=gm, bevel=0.05)
    parts.append(body)
    parts.append(torus('RimF', (0, -0.12, 0), 0.92, 0.06, axis='Y', mat=gm, major=96))
    inner = cyl('Inner', (0, -0.115, 0), 0.86, 0.01, axis='Y', verts=96, mat=deep)
    parts.append(inner)
    st = puffy('Star', star_pts(0.58, 0.27), gm, extrude=0.03, bevel=0.06)
    st.location = (0, -0.16, 0)
    parts.append(st)
    # grooved edge: thin ribs round the rim
    for k in range(64):
        a = 2 * math.pi * k / 64
        r = box(f'Rib{k}', (math.cos(a) * 1.005, 0, math.sin(a) * 1.005), (0.03, 0.2, 0.03), deep)
        r.rotation_euler = (0, -a, 0)
        parts.append(r)
    return parts, dict(turn=-28, tilt=8, frame=[body], fill=0.84, expo=-0.10)


def make_star(full=True):
    if full:
        m = S.principled('StarGold', (*S.srgb((1.0, 0.82, 0.16)), 1), rough=0.2, metal=0.45, coat=1.0, coat_rough=0.03, emission='#ffb300', emission_strength=0.35)
    else:
        m = S.principled('StarEmpty', '#3a4150', rough=0.35, coat=0.8, coat_rough=0.1)
    o = puffy('Star', star_pts(1.0, 0.47), m, extrude=0.16, bevel=0.12)
    return [o], dict(turn=-18, tilt=6, expo=-0.30)


MAKERS = {
    'energy': make_energy, 'world': make_world, 'fame': make_fame, 'happiness': make_happiness,
    'heart': make_heart, 'money': make_money,
    'star-full': lambda: make_star(True), 'star-empty': lambda: make_star(False),
}


def main():
    a = S.args()
    name, out = a[0], a[1]
    samples = int(a[2]) if len(a) > 2 else 48
    size = int(a[3]) if len(a) > 3 else 512
    S.reset()
    S.setup_render((size, size), samples)
    S.world(0.55, top=(0.75, 0.80, 0.95), bottom=(0.10, 0.10, 0.14))
    parts, c = MAKERS[name]()
    # one turn for the whole icon so its thickness shows
    R = Matrix.Rotation(math.radians(c.get('tilt', 0)), 4, 'X') @ Matrix.Rotation(math.radians(c.get('turn', 0)), 4, 'Z')
    for o in parts:
        o.matrix_world = R @ o.matrix_world
    bpy.context.scene.view_settings.exposure = c.get('expo', -0.3)
    bpy.context.view_layer.update()
    S.studio_lights(scale=2.6, aim=(0, 0, 0), key=1.0)
    cam = S.camera((0, -9, 1.6), (0, 0, 0), lens=90)
    frame = [p for p in (c.get('frame') or parts) if p.type == 'MESH']
    S.frame_objects(cam, frame, fill=c.get('fill', 0.86))
    S.render(out)


if __name__ == '__main__':
    main()
