"use client";

/**
 * 3D TEST AREA (Harry, 2 Oct 2026, v0.24): "a 3D Test Area page on the site:
 * a list of every cutscene / 3D area being built (the Blender 3D walk-around
 * shop moves in here), plus an organised store of all the 3D Blender assets."
 *
 * Two tabs. Scenes: one picture card per cutscene or 3D area (lib/star/
 * area3d.ts), tap to open it. Assets: every 3D / Blender file the site ships,
 * in folders by kind (lib/star/assets3dManifest.ts, generated by
 * scripts/assets3d-manifest.mjs), each with a preview and its file path.
 * Nothing here touches a career and nothing is saved.
 */
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import PageGuide from "@/components/admin/PageGuide";
import { SCENES_3D, type Scene3d, type Scene3dStatus } from "@/lib/star/area3d";
import { ASSETS_3D, type Asset3dFile, type Asset3dFolder } from "@/lib/star/assets3dManifest";

const BG = "#05070d";
const INK = "#f2f5f9";
const MUTED = "#8a97aa";
const LINE = "rgba(255,255,255,0.09)";

const STATUS_COLOUR: Record<Scene3dStatus, string> = {
  Prototype: "#fbbf24",
  "Test page": "#34d399",
  Pictures: "#60a5fa",
  Planned: "#94a3b8",
  Proposal: "#c084fc",
};

function kb(bytes: number) {
  return bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;
}

function fileName(path: string) {
  return path.slice(path.lastIndexOf("/") + 1);
}

function SceneCard({ s }: { s: Scene3d }) {
  const [broken, setBroken] = useState(false);
  const body = (
    <div style={{ position: "relative", aspectRatio: "16 / 10", overflow: "hidden", background: "linear-gradient(160deg,#1b2433,#0b0f17)" }}>
      {s.thumb && !broken ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={s.thumb} alt="" onError={() => setBroken(true)} style={{ width: "100%", height: "100%", objectFit: "cover", display: "block" }} />
      ) : (
        <div style={{ position: "absolute", inset: 0, display: "grid", placeItems: "center", fontSize: 40, opacity: 0.35 }}>◆</div>
      )}
      <div style={{ position: "absolute", inset: 0, background: "linear-gradient(180deg, rgba(0,0,0,0) 45%, rgba(0,0,0,.82) 100%)" }} />
      <span style={{ position: "absolute", top: 10, left: 10, fontSize: 11, fontWeight: 800, letterSpacing: 0.4, padding: "3px 7px", background: "rgba(0,0,0,.6)", color: STATUS_COLOUR[s.status], border: `1px solid ${STATUS_COLOUR[s.status]}55` }}>
        {s.status.toUpperCase()}
      </span>
      <div style={{ position: "absolute", left: 12, right: 12, bottom: 10 }}>
        <div style={{ fontSize: 19, fontWeight: 900, color: INK, lineHeight: 1.1 }}>{s.title}{s.href ? " ›" : ""}</div>
        <div style={{ fontSize: 13, color: "#cbd5e1", marginTop: 3, lineHeight: 1.3 }}>{s.line}</div>
      </div>
    </div>
  );
  return (
    <div data-scene={s.id} style={{ borderBottom: `1px solid ${LINE}` }}>
      {s.href ? <Link href={s.href} style={{ textDecoration: "none", display: "block" }}>{body}</Link> : body}
      <div style={{ padding: "6px 12px 10px", fontSize: 11, color: MUTED, fontFamily: "ui-monospace, monospace", wordBreak: "break-word" }}>{s.files}</div>
    </div>
  );
}

function Preview({ folder, file, size }: { folder: Asset3dFolder; file: Asset3dFile; size: number }) {
  const box: React.CSSProperties = { width: size, height: size, display: "block", objectFit: "contain", background: "repeating-conic-gradient(#1a2130 0% 25%, #121825 0% 50%) 50% / 16px 16px" };
  if (folder.kind === "image") {
    // eslint-disable-next-line @next/next/no-img-element
    return <img src={file.path} alt={fileName(file.path)} loading="lazy" style={box} />;
  }
  if (folder.kind === "video") {
    return <video src={file.path} poster={file.path.replace(/\.mp4$/, ".jpg")} muted loop playsInline autoPlay={size > 200} style={box} />;
  }
  return (
    <div style={{ ...box, display: "grid", placeItems: "center", color: MUTED, fontSize: 12, textAlign: "center" }}>
      <div><div style={{ fontSize: 30 }}>⬢</div>3D model<br />(.glb)</div>
    </div>
  );
}

function AssetStore() {
  const [open, setOpen] = useState<string>(ASSETS_3D.find((f) => f.files.length)?.id ?? ASSETS_3D[0].id);
  const [big, setBig] = useState<{ folder: Asset3dFolder; file: Asset3dFile } | null>(null);
  const [copied, setCopied] = useState(false);
  const folder = ASSETS_3D.find((f) => f.id === open) ?? ASSETS_3D[0];
  const total = useMemo(() => ASSETS_3D.reduce((n, f) => n + f.files.length, 0), []);

  useEffect(() => { setCopied(false); }, [big]);

  return (
    <div>
      <div style={{ display: "flex", gap: 6, overflowX: "auto", padding: "10px 12px", borderBottom: `1px solid ${LINE}`, scrollbarWidth: "none" }}>
        {ASSETS_3D.map((f) => (
          <button
            key={f.id}
            data-folder={f.id}
            onClick={() => setOpen(f.id)}
            style={{
              flex: "0 0 auto", padding: "7px 10px", fontSize: 13, fontWeight: 700, cursor: "pointer",
              background: f.id === open ? "#f2f5f9" : "rgba(255,255,255,0.06)", color: f.id === open ? "#05070d" : INK,
              border: "none", borderRadius: 2, whiteSpace: "nowrap",
            }}
          >
            📁 {f.title} <span style={{ opacity: 0.6 }}>{f.files.length}</span>
          </button>
        ))}
      </div>
      <div style={{ padding: "10px 12px 2px" }}>
        <div style={{ fontSize: 12, color: MUTED }}>Made by: <span style={{ fontFamily: "ui-monospace, monospace", color: "#cbd5e1" }}>{folder.made}</span></div>
        {folder.note && <div style={{ fontSize: 12, color: MUTED, marginTop: 2 }}>{folder.note}</div>}
      </div>
      {folder.files.length === 0 ? (
        <div style={{ padding: 24, color: MUTED, fontSize: 14 }}>Empty for now.</div>
      ) : (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(112px, 1fr))", gap: 8, padding: 12 }}>
          {folder.files.map((file) => (
            <button key={file.path} data-asset={file.path} onClick={() => setBig({ folder, file })} style={{ all: "unset", cursor: "pointer", display: "block", minWidth: 0 }}>
              <Preview folder={folder} file={file} size={112} />
              <div style={{ fontSize: 10.5, color: "#cbd5e1", fontFamily: "ui-monospace, monospace", marginTop: 3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{fileName(file.path)}</div>
              <div style={{ fontSize: 10, color: MUTED }}>{kb(file.bytes)}</div>
            </button>
          ))}
        </div>
      )}
      <div style={{ padding: "4px 12px 90px", fontSize: 11, color: MUTED }}>{total} files in {ASSETS_3D.length} folders.</div>

      {big && (
        <div onClick={() => setBig(null)} style={{ position: "fixed", inset: 0, background: "rgba(2,4,8,.92)", zIndex: 60, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", padding: 16 }}>
          <div onClick={(e) => e.stopPropagation()} style={{ width: "100%", maxWidth: 520 }}>
            <Preview folder={big.folder} file={big.file} size={Math.min(520, typeof window !== "undefined" ? window.innerWidth - 32 : 358)} />
            <div style={{ marginTop: 10, fontSize: 13, color: INK, fontFamily: "ui-monospace, monospace", wordBreak: "break-all" }}>public{big.file.path}</div>
            <div style={{ fontSize: 12, color: MUTED, marginTop: 2 }}>{kb(big.file.bytes)} · {big.folder.title}</div>
            <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
              <button
                onClick={() => { navigator.clipboard?.writeText(`public${big.file.path}`).then(() => setCopied(true), () => setCopied(false)); }}
                style={{ flex: 1, padding: "10px 0", fontWeight: 800, background: "#f2f5f9", color: "#05070d", border: "none", borderRadius: 2, cursor: "pointer" }}
              >
                {copied ? "Copied ✓" : "Copy path"}
              </button>
              <a href={big.file.path} target="_blank" rel="noreferrer" style={{ flex: 1, padding: "10px 0", fontWeight: 800, textAlign: "center", background: "rgba(255,255,255,.08)", color: INK, textDecoration: "none", borderRadius: 2 }}>Open file</a>
              <button onClick={() => setBig(null)} style={{ width: 48, fontWeight: 800, background: "rgba(255,255,255,.08)", color: INK, border: "none", borderRadius: 2, cursor: "pointer" }}>✕</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default function Area3dPage() {
  const [tab, setTab] = useState<"scenes" | "assets">("scenes");
  return (
    <main style={{ minHeight: "100vh", background: BG, color: INK, fontFamily: "system-ui, -apple-system, Segoe UI, sans-serif" }}>
      <div style={{ maxWidth: 720, margin: "0 auto" }}>
        <header style={{ display: "flex", alignItems: "center", gap: 10, padding: "12px 12px 0" }}>
          <Link href="/star-play-dev" aria-label="Back" style={{ color: INK, textDecoration: "none", fontSize: 22, width: 32 }}>‹</Link>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 900 }}>3D Test Area</h1>
        </header>
        <div style={{ display: "flex", margin: "12px 12px 0", border: `1px solid ${LINE}` }}>
          {(["scenes", "assets"] as const).map((t) => (
            <button
              key={t}
              data-tab={t}
              onClick={() => setTab(t)}
              style={{ flex: 1, padding: "10px 0", fontSize: 14, fontWeight: 800, cursor: "pointer", border: "none", background: tab === t ? "#f2f5f9" : "transparent", color: tab === t ? "#05070d" : INK }}
            >
              {t === "scenes" ? `Scenes (${SCENES_3D.length})` : "Assets"}
            </button>
          ))}
        </div>
        <div style={{ marginTop: 12 }}>
          {tab === "scenes" ? (
            <div style={{ paddingBottom: 80 }}>{SCENES_3D.map((s) => <SceneCard key={s.id} s={s} />)}</div>
          ) : (
            <AssetStore />
          )}
        </div>
      </div>
      <PageGuide page="/star-3d-area-dev" />
    </main>
  );
}
