"""Turn the club spreadsheets you've given into lib/star/data/clubProfileData.ts.

  python scripts/club-data/build_club_profile_data.py

Sources, kept in the repo exactly as given (never edit them; add a new file
and a new block below instead):
  lib/star/data/football-club-database.csv
      14 Sep 2026: the 125-club sheet (Premier League, Championship, Europe,
      5 League One clubs). 16 columns, has a header row.
  lib/star/data/sources/national_league_north_south_full_dataset_2026-10.xlsx
      2 Oct 2026: National League North and South (48 clubs) plus the 8 Step 3
      clubs waiting below them. 44 columns, NO header row: the columns are in
      the order of the list Mikey was given (see REGIONAL_COLUMNS).

The output is data only (strings exactly as given). lib/star/data/clubProfiles.ts
turns it into the profile the game and /admin/clubs read.
"""
import csv, json, os, sys
import openpyxl

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "lib", "star", "data", "clubProfileData.ts")

REGIONAL_COLUMNS = [
    "division", "club", "fullName", "nickname", "founded", "country",
    "homeShirt", "homeTrim", "homePattern", "awayShirt", "awayTrim", "awayPattern",
    "badge1", "badge2", "badge3", "badgeStyle", "stadium", "capacity",
    "training", "youth", "leagueTitles", "domesticCups", "europeanTrophies",
    "currentRep", "historicalRep", "ballonDor", "transferSpending", "transferStrategy",
    "clubSize", "avgRating",
    "rival1", "rival1Tier", "rival1Derby", "rival2", "rival2Tier", "rival2Derby", "rival3", "rival3Tier", "rival3Derby",
    "winChant", "playerChant", "manager", "formation", "notes",
]


def text(v):
    if v is None:
        return ""
    if isinstance(v, float) and v.is_integer():
        v = int(v)
    return str(v).strip().replace("�", "-")


def regional():
    path = os.path.join(ROOT, "lib", "star", "data", "sources", "national_league_north_south_full_dataset_2026-10.xlsx")
    wb = openpyxl.load_workbook(path, data_only=True)
    ws = wb["Full Dataset"]
    rows = []
    for r in ws.iter_rows(values_only=True):
        if not r or not r[1]:
            continue
        rows.append({k: text(v) for k, v in zip(REGIONAL_COLUMNS, r)})
    bench = {text(a): text(b) for a, b in wb["Existing Benchmarks"].iter_rows(min_row=2, values_only=True) if a}
    notes = {text(a): text(b) for a, b in wb["Sources & Notes"].iter_rows(min_row=2, values_only=True) if a}
    return rows, bench, notes


def club_sheet():
    path = os.path.join(ROOT, "lib", "star", "data", "football-club-database.csv")
    return [{k: (v or "").strip() for k, v in r.items()} for r in csv.DictReader(open(path, encoding="utf8"))]


rows, bench, notes = regional()
sheet = club_sheet()
with open(OUT, "w", encoding="utf8") as f:
    f.write("// GENERATED by scripts/club-data/build_club_profile_data.py — do not edit by hand.\n")
    f.write("// The club spreadsheets exactly as given. Read through lib/star/data/clubProfiles.ts.\n\n")
    f.write("/** 14 Sep 2026: the 125-club sheet (lib/star/data/football-club-database.csv), every column. */\n")
    f.write("export const CLUB_SHEET_2026_09: Record<string, string>[] = " + json.dumps(sheet, ensure_ascii=False, indent=1) + ";\n\n")
    f.write("/** 2 Oct 2026: National League North/South and the Step 3 clubs below them. */\n")
    f.write("export const REGIONAL_SHEET_2026_10: Record<string, string>[] = " + json.dumps(rows, ensure_ascii=False, indent=1) + ";\n\n")
    f.write("export const REGIONAL_BENCHMARKS_2026_10: Record<string, string> = " + json.dumps(bench, ensure_ascii=False, indent=1) + ";\n\n")
    f.write("export const REGIONAL_NOTES_2026_10: Record<string, string> = " + json.dumps(notes, ensure_ascii=False, indent=1) + ";\n")
print(f"wrote {OUT}: {len(sheet)} + {len(rows)} clubs")
